server:
  port: 8083
  error:
    include-message: always
cors:
  allowed-methods: "*"
  allowed-origins: "*"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: diego
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true