CREATE TABLE customer
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    age   INTEGER                                 NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);